### ISSUE TITLE
Second call is mute

### ISSUE THREAD

**Issue by telmedola** [vanbui1995/react-sipjs#17]
Hi. Thank you very much for STUN, it worked correctly.

After configuring STUN server and granting permission to the mic and speaker, the call completed successfully and both sides heard each other.
On the second call, the audio went silent. I decided to reset the permissions and after granting new permission, the call went through. Not the second again.
As it turns out, something is linked to the permission, and only by granting it again will the audio of the connection flow between the two ends.

**Comment by newlflextv** [comment]
Hi can you please share the sample code ? we have implemented the stun but its getting delay for 5sec to connect the audio on both end after call established. 
we don't have any firewall rules and no restriction
RTT is good no delay

**Comment by telmedola** [comment]
The call works great the first time. I can hear the other side, everything is normal.
But when I go to do the second one, the connection goes silent.
When you reset the permissions(mic and speaker), it works again.
The example is the same "full-example" from the repository, I just updated it to version 0.0.6

[example.zip](https://github.com/user-attachments/files/17844352/example.zip)

**Comment by vanbui1995** [comment]
@telmedola can you give a detail step by step to replicate this issue, video record may be good, any log from console would be great!

**Comment by telmedola** [comment]
Yeah, sure.
[localhost-1732917621195.log](https://github.com/user-attachments/files/17963204/localhost-1732917621195.log)
link the video: https://drive.google.com/file/d/1y8f8J6FNMOHQv5rsPP_vOJLkYzveXhYL/view?usp=sharing
Thanks a lot!

**Comment by vanbui1995** [comment]
@telmedola 
as i researched, seem that's not problem from the package, here's an answer from gpt, you can follow to troubleshoot your issue:

When using STUN, the browser may require you to reset permissions (e.g., microphone or speaker access) to hear audio due to how the browser manages device permissions and network changes. Here’s why:

1. Browser Permission Management
Permissions Becoming Invalid: When STUN is used, it may change the device's public IP or network configuration (e.g., NAT traversal). Browsers often treat such changes as new sessions, invalidating previous permissions to ensure security.
Re-granting Access: Resetting permissions ensures the application can continue to access the microphone or speakers after these changes.
2. STUN and Connection Reconfiguration
IP Address Changes: STUN enables the device to discover its public IP and NAT details. If these parameters (IP or port) change, the browser might perceive this as a security concern and reset the media session.
Reinitializing RTP Streams: When STUN updates connection details (IP or UDP port for RTP streams), the browser may need to renegotiate the media session, which could involve re-confirming permissions.
3. Browser Security Policies
Modern browsers like Chrome and Firefox are designed to prioritize user security. If a connection or device configuration changes unexpectedly, browsers may revoke access to avoid potential abuse.

Solutions that we recommend to you after research:

- Use HTTPS:Ensure your application runs over HTTPS. Both STUN and WebRTC require secure connections for stable and secure operation, you can deploy to somewhere eg: netlify and test again
- Check firewall & NAT, check your infra: check if there is any changes between your 2 calls: (IP or UDP port for RTP streams)

If your setup, infra are not applicable to make 2 things work as expected, you have to add ask permission for any new call 🙏🏽
